# Generated by Django 5.2 on 2025-04-12 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardProject', '0004_remove_post_image_post_writer_alter_post_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('overview', models.TextField()),
                ('release_date', models.DateField()),
                ('vote_average', models.FloatField()),
                ('genres', models.CharField(max_length=100)),
            ],
        ),
    ]
