# Generated by Django 5.2 on 2025-04-12 18:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardProject', '0009_rename_movie_movies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movies',
            options={'verbose_name_plural': 'Movies'},
        ),
        migrations.RemoveField(
            model_name='reviewcomment',
            name='review',
        ),
        migrations.AddField(
            model_name='reviewcomment',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_comments', to='BoardProject.movies'),
        ),
        migrations.AlterField(
            model_name='movies',
            name='genres',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='movies',
            name='overview',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='movies',
            name='release_date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movies',
            name='vote_average',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='review',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='BoardProject.movies'),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='reviewcomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
