# Generated by Django 4.2.20 on 2025-04-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_review_rating'),
        ('BoardProject', '0006_comment_parent'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Movie',
        ),
        migrations.AddField(
            model_name='post',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='movies.movie'),
        ),
    ]
