# Generated by Django 5.2 on 2025-04-12 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardProject', '0005_movie'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
