# Generated by Django 5.2 on 2025-04-12 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardProject', '0008_movie_alter_review_movie_delete_movies'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Movies',
        ),
    ]
