# Generated by Django 5.2 on 2025-04-12 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_tmdb_id'),
    ]

    operations = [
    ]
